/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory_system;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Sandun
 */
public class menu extends javax.swing.JFrame {
    JpanelLoader jpload = new JpanelLoader();
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        user();
    }
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        add_user = new javax.swing.JButton();
        p_plan = new javax.swing.JButton();
        products = new javax.swing.JButton();
        is_m = new javax.swing.JButton();
        add_m = new javax.swing.JButton();
        new_m = new javax.swing.JButton();
        new_cus = new javax.swing.JButton();
        od_tab = new javax.swing.JButton();
        od_plc = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        bg_image = new javax.swing.JLabel();
        f_cast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, 50));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, 50));

        name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 30));

        add_user.setText("Add User");
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });
        jPanel1.add(add_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, 50));

        p_plan.setBackground(new java.awt.Color(204, 255, 255));
        p_plan.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        p_plan.setForeground(new java.awt.Color(0, 0, 153));
        p_plan.setText("Product Planning");
        p_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_planActionPerformed(evt);
            }
        });
        jPanel1.add(p_plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 50));

        products.setBackground(new java.awt.Color(204, 255, 255));
        products.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        products.setForeground(new java.awt.Color(0, 0, 153));
        products.setText("Products");
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        jPanel1.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 50));

        is_m.setBackground(new java.awt.Color(204, 255, 255));
        is_m.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        is_m.setForeground(new java.awt.Color(0, 0, 153));
        is_m.setText("Inventory");
        is_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                is_mActionPerformed(evt);
            }
        });
        jPanel1.add(is_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 250, 50));

        add_m.setBackground(new java.awt.Color(204, 255, 255));
        add_m.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        add_m.setForeground(new java.awt.Color(0, 0, 153));
        add_m.setText("BOM");
        add_m.setPreferredSize(new java.awt.Dimension(101, 22));
        add_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_mActionPerformed(evt);
            }
        });
        jPanel1.add(add_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 250, 50));

        new_m.setBackground(new java.awt.Color(204, 255, 255));
        new_m.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        new_m.setForeground(new java.awt.Color(0, 0, 153));
        new_m.setText("New Material");
        new_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_mActionPerformed(evt);
            }
        });
        jPanel1.add(new_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 50));

        new_cus.setBackground(new java.awt.Color(204, 255, 255));
        new_cus.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        new_cus.setForeground(new java.awt.Color(0, 0, 153));
        new_cus.setText("New Customer");
        new_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_cusActionPerformed(evt);
            }
        });
        jPanel1.add(new_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 50));

        od_tab.setBackground(new java.awt.Color(204, 255, 255));
        od_tab.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        od_tab.setForeground(new java.awt.Color(0, 0, 153));
        od_tab.setText("MRP");
        od_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                od_tabActionPerformed(evt);
            }
        });
        jPanel1.add(od_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 250, 50));

        od_plc.setBackground(new java.awt.Color(204, 255, 255));
        od_plc.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        od_plc.setForeground(new java.awt.Color(0, 0, 153));
        od_plc.setText("Order Placing");
        od_plc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                od_plcActionPerformed(evt);
            }
        });
        jPanel1.add(od_plc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));

        display.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_system/assests/LINE_Disney_Toy_Company_pre.png"))); // NOI18N
        display.add(jLabel1);

        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 830, 670));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        from.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 340, 50));

        bg_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_system/assests/bg.png"))); // NOI18N
        jPanel1.add(bg_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));

        f_cast.setBackground(new java.awt.Color(204, 255, 255));
        f_cast.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        f_cast.setForeground(new java.awt.Color(0, 0, 153));
        f_cast.setText("ForeCasting");
        f_cast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_castActionPerformed(evt);
            }
        });
        jPanel1.add(f_cast, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void is_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_is_mActionPerformed
        // TODO add your handling code here:
        issues_material is_mat =new issues_material();
        
        jpload.jPanelLoader(display, is_mat);
    }//GEN-LAST:event_is_mActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null, "Do you want to exit Application","SELECT",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login sp = new login();
        sp.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void new_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_mActionPerformed
        // TODO add your handling code here:
        new_mat new_m =new new_mat();
        
        jpload.jPanelLoader(display, new_m);
    }//GEN-LAST:event_new_mActionPerformed

    private void add_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_mActionPerformed
        // TODO add your handling code here:
        add_mat add_m =new add_mat();
        
        jpload.jPanelLoader(display, add_m);
    }//GEN-LAST:event_add_mActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
        Product pro=new Product();
        
        jpload.jPanelLoader(display, pro);
    }//GEN-LAST:event_productsActionPerformed

    private void p_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_planActionPerformed
        // TODO add your handling code here:
        product_planning pro_plan =new product_planning();
        
        jpload.jPanelLoader(display, pro_plan);
    }//GEN-LAST:event_p_planActionPerformed

    private void new_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_cusActionPerformed
        // TODO add your handling code here:
        new_cust new_customer =new new_cust();
        
        jpload.jPanelLoader(display, new_customer);
    }//GEN-LAST:event_new_cusActionPerformed

    private void od_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_od_tabActionPerformed
        // TODO add your handling code here:
        order_table o_table =new order_table();
        
        jpload.jPanelLoader(display, o_table);
    }//GEN-LAST:event_od_tabActionPerformed

    private void od_plcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_od_plcActionPerformed
        // TODO add your handling code here:
        order_placing o_plc =new order_placing();
        
        jpload.jPanelLoader(display, o_plc);
    }//GEN-LAST:event_od_plcActionPerformed

    private void f_castActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_castActionPerformed
        // TODO add your handling code here:
        forecasting fc =new forecasting();
        
        jpload.jPanelLoader(display, fc);
    }//GEN-LAST:event_f_castActionPerformed

    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
        // TODO add your handling code here:
        add_user add =new add_user();
        
        jpload.jPanelLoader(display, add);
    }//GEN-LAST:event_add_userActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened
public void user(){
  

    name.setText(login.name);
    
    String nm = name.getText();

    Statement stmt;
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM users where user_id ='"+nm+"'");
      
        while(rs.next()){
        this.from.setText(rs.getString(3));
        String ss = from.getText();
        if(ss.equals("WareHouse")){
            add_user.setEnabled(false);
            new_cus.setEnabled(false);
            products.setEnabled(false);
            od_plc.setEnabled(false);
            new_m.setEnabled(false);
            add_m.setEnabled(false);
            p_plan.setEnabled(false);
            od_tab.setEnabled(false);
          
            
        }
        if(ss.equals("Financial")){
            add_user.setEnabled(false);
           
            products.setEnabled(false);
            
            new_m.setEnabled(false);
            
            p_plan.setEnabled(false);
            od_tab.setEnabled(false);
              is_m.setEnabled(false);
        }
        if(ss.equals("Production")){
            add_user.setEnabled(false);
            new_cus.setEnabled(false);
            od_plc.setEnabled(false);
            
            add_m.setEnabled(false);
             is_m.setEnabled(false);
        }
        if(ss.equals("Marketing")){
            add_user.setEnabled(false);
            new_cus.setEnabled(false);
            products.setEnabled(false);
            od_plc.setEnabled(false);
            new_m.setEnabled(false);
            add_m.setEnabled(false);
             p_plan.setEnabled(false);
            od_tab.setEnabled(false);
            is_m.setEnabled(false);
        }
        }
          rs.close();
    }catch(SQLException k){
                  
     }
        
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_m;
    private javax.swing.JButton add_user;
    private javax.swing.JLabel bg_image;
    private javax.swing.JPanel display;
    private javax.swing.JButton exit;
    private javax.swing.JButton f_cast;
    public javax.swing.JLabel from;
    private javax.swing.JButton is_m;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    public javax.swing.JLabel name;
    private javax.swing.JButton new_cus;
    private javax.swing.JButton new_m;
    private javax.swing.JButton od_plc;
    private javax.swing.JButton od_tab;
    private javax.swing.JButton p_plan;
    private javax.swing.JButton products;
    // End of variables declaration//GEN-END:variables
}
